### ISSUE TITLE
Permission denied: '/dev/log'

### ISSUE THREAD

**Issue by michaelsstuff** [eea/eea.docker.memcached#1]
Hi,

I started it with docker-compse conf:

  memcached:
    image: eeacms/memcached:latest
    container_name: memcached
    ports:
      - 11211:11211
    environment:
      - MEMCACHED_VERBOSE

And i got the following output:

memcached        | syslog service cannot be started: [Errno 13] Permission denied: '/dev/log'
memcached        | command service cannot be started: [Errno 13] Permission denied

**Comment by avoinea** [comment]
This is just a warning, from chaperone process manager inside container.
 
Also note that this image is not maintained anymore. You can use [the official memcached](https://hub.docker.com/_/memcached/) image and pass the arguments via CMD like:

    $ docker run memcached -m 2048

See more memcached options with:

    $ docker run --rm memcached --help
